preprocessors:
  - name: skip_and_merge
    config:
      skip_types:
        - page_number
  - name: dual_dialogue
  - name: extract_dialogue_parentheticals
    config:
      max_words: 10

processors:
  - name: skip_empty
    config:
      skip_types:
        - page_number
  - name: text_substitution
    config:
      substitutions:
        - from: "CONT'D"
          to: "CONTINUED"
          fields:
            - text
        - from: "V.O."
          to: "VOICE OVER"
          fields:
            - text
        - from: "INT."
          to: "INTERIOR"
          fields:
            - text
        - from: "EXT."
          to: "EXTERIOR"
          fields:
            - text
        - from: "O.S."
          to: "OFF SCREEN"
          fields:
            - text
        - from: "O.C."
          to: "OFF CAMERA"
          fields:
            - text
  - name: pattern_replace
    config:
      replacements:
        - match_field: "type"
          match_pattern: "^dialogue_modifier$"
          replace_field: "speaker"
          replace_pattern: ".*"
          replace_string: ""
          notes: >-
            Replace the speaker for "dialogue modifiers" -- parentheticals in dialogue, e.g. "(gasps)" --
            with the narrator / default speaker by blanking their speaker
        - match_field: "type"
          match_pattern: "^dialogue_modifier$"
          replace_field: "text"
          replace_pattern: '^\(|\)$'
          replace_string: ""
          notes: >-
            Remove the parentheses around "dialogue modifiers" -- parentheticals in dialogue, e.g. "(gasps)" --
            as some TTS providers try to generate a sound effect instead of reading the literal text
            when it is wrapped in parentheses
        - match_field: "type"
          match_pattern: "^speaker_attribution$"
          replace_field: "text"
          replace_pattern: '\(([^\)]*)\)'
          replace_string: '\1'
          notes: >-
            Remove the parentheses in speaker attributions -- e.g. TOM (CONTINUED) --
            as some TTS providers (such as OpenAI) seem to occasionally drop
            parentheticals in short phrases.
        - match_field: "type"
          match_pattern: "^scene_heading$"
          replace_field: "text"
          replace_pattern: '^(?P<scene_num>[A-Z]?\d+(\.\d+)?)\b(.*)\b(?P=scene_num)$'
          replace_string: '\1\3'
          notes: >-
            Remove the second occurrence of the scene number in scene headings, e.g.
            "22 INT. HEADQUARTERS -- NIGHT 22" -> "22 INT. HEADQUARTERS -- NIGHT".
  - name: capitalization_transform
    config:
      transformations:
        - chunk_type: speaker_attribution
          case: sentence_case
          notes: >-
            Some TTS providers (like OpenAI) have trouble generating audio for short
            ALL CAPS strings, which is exactly how speaker attributions are formatted
            (e.g. DAVE OFF SCREEN). Sentence case reads as "Dave off screen".
        - chunk_type: scene_heading
          case: sentence_case
        - chunk_type: dialogue_modifier
          case: lower_case
