preprocessors:
  - name: skip_and_merge
    config:
      skip_types:
        - page_number
  - name: dual_dialogue
  - name: extract_dialogue_parentheticals
    config:
      max_words: 10

processors:
  - name: skip_empty
    config:
      skip_types:
        - page_number
  - name: text_substitution
    config:
      substitutions:
        - from: "CONT'D"
          to: "CONTINUED"
          fields:
            - text
        - from: "V.O."
          to: "VOICE OVER"
          fields:
            - text
        - from: "INT."
          to: "INTERIOR"
          fields:
            - text
        - from: "EXT."
          to: "EXTERIOR"
          fields:
            - text
        - from: "O.S."
          to: "OFF SCREEN"
          fields:
            - text
        - from: "O.C."
          to: "OFF CAMERA"
          fields:
            - text
  - name: pattern_replace
    config:
      replacements:
        # Replace the speaker for "dialogue modifiers" -- parenteticals in dialogue, e.g. "(gasps)" --
        # with an empty speaker, so that these are read using the narrator / default speaker
        - match_field: "type"
          match_pattern: "^dialogue_modifier$"
          replace_field: "speaker"
          replace_pattern: ".*"
          replace_string: ""
        # Remove the parenthesis in "dialogue modifiers" -- parenteticals in dialogue, e.g. "(gasps)" --
        # as some TTS providers try to generate a sound instead of providing the literal text when
        # it is wrapped in parentheses
        - match_field: "type"
          match_pattern: "^dialogue_modifier$"
          replace_field: "text"
          replace_pattern: '^\(|\)$'
          replace_string: ""
        # Remove the parenthesis in "speaker attributions" -- e.g. TOM (CONTINUED) --
        # as some TTS providers (such as OpenAI) seem to occasionally drop parentheticals
        # in short phrases
        - match_field: "type"
          match_pattern: "^speaker_attribution$"
          replace_field: "text"
          replace_pattern: '\(([^\)]*)\)'
          replace_string: '\1'
        # Remove second occurrence of scene number in scene headings,
        # e.g. "22 INT. HEADQUARTERS -- NIGHT 22" -> "22 INT. HEADQUARTERS -- NIGHT"
        - match_field: "type"
          match_pattern: "^scene_heading$"
          replace_field: "text"
          replace_pattern: '^(?P<scene_num>[A-Z]?\d+(\.\d+)?)\b(.*)\b(?P=scene_num)$'
          replace_string: '\1\3'
  - name: capitalization_transform
    config:
      # Some TTS providers (like OpenAI) have trouble generating audio for short ALL CAPS
      # strings, which is exactly how speaker attributions are formatted (e.g. DAVE OFF SCREEN).
      # This will change the string to "sentence case", e.g. "Dave off screen"
      transformations:
        - chunk_type: speaker_attribution
          case: sentence_case
        - chunk_type: scene_heading
          case: sentence_case
        - chunk_type: dialogue_modifier
          case: lower_case
