preprocessors:
  - name: skip_and_merge
    config:
      skip_types:
        - page_number
  - name: dual_dialog

processors:
  - name: skip_empty
    config:
      skip_types:
        - page_number
  - name: text_substitution
    config:
      substitutions:
        - from: "CONT’D"
          to: "CONTINUED"
          fields:
            - text
        - from: "CONT'D"
          to: "CONTINUED"
          fields:
            - text
        - from: "V.O."
          to: "VOICE OVER"
          fields:
            - text
        - from: "INT."
          to: "INTERIOR"
          fields:
            - text
        - from: "EXT."
          to: "EXTERIOR"
          fields:
            - text
        - from: "O.S."
          to: "OFF SCREEN"
          fields:
            - text
  - name: pattern_replace
    config:
      replacements:
        # Replace the speaker for "dialog modifiers" -- parenteticals in dialog, e.g. "(gasps)" --
        # with an empty speaker, so that these are read using the narrator / default speaker
        - match_field: "type"
          match_pattern: "^dialog_modifier$"
          replace_field: "speaker"
          replace_pattern: ".*"
          replace_string: ""
        # Remove the parenthesis in "dialog modifiers" -- parenteticals in dialog, e.g. "(gasps)" --
        # as some TTS providers try to generate a sound instead of providing the literal text when
        # it is wrapped in parentheses
        - match_field: "type"
          match_pattern: "^dialog_modifier$"
          replace_field: "text"
          replace_pattern: '^\(|\)$'
          replace_string: ""
        # Remove the parenthesis in "speaker attributions" -- e.g. TOM (CONTINUED) --
        # as some TTS providers (such as OpenAI) seem to occasionally drop parentheticals
        # in short phrases
        - match_field: "type"
          match_pattern: "^speaker_attribution$"
          replace_field: "text"
          replace_pattern: '\(([^\)]*)\)'
          replace_string: '\1'
