processors:
  - name: skip_empty
    config:
      skip_types:
        - page number
  - name: text_substitution
    config:
      substitutions:
        - from: "CONT’D"
          to: "CONTINUED"
          fields:
            - text
        - from: "CONT'D"
          to: "CONTINUED"
          fields:
            - text
        - from: "V.O."
          to: "VOICE OVER"
          fields:
            - text
        - from: "INT."
          to: "INTERIOR"
          fields:
            - text
        - from: "EXT."
          to: "EXTERIOR"
          fields:
            - text
        - from: "O.S."
          to: "OFF SCREEN"
          fields:
            - text
  - name: pattern_replace
    config:
      replacements:
        # Replace the speaker for "dialog modifiers" -- parenteticals in dialog, e.g. "(gasps)" --
        # with an empty speaker, so that these are read using the narrator / default speaker
        - match_field: "type"
          match_pattern: "^dialog modifier$"
          replace_field: "speaker"
          replace_pattern: ".*"
