"""Generation of seeded text processor configuration files.

At parse time each screenplay gets its own standalone text processor config,
seeded from the user's global default config (if present) or the shipped
default config. A standalone config fully replaces the shipped default at
runtime (see utils.get_text_processor_configs), which makes the processing
pipeline for a screenplay explicit and freely editable.

Seed provenance is recorded in a top-level ``sts_metadata`` block, which
TextProcessorManager ignores. The recorded hash of the shipped default's
pipeline allows detecting configs that were seeded from an older version of
the defaults.
"""

import hashlib
import json
import os
from io import StringIO
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

import yaml
from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap

from .._version import __version__
from ..utils.logging import get_screenplay_logger
from ..voice_library.constants import get_user_workspace_dir
from .utils import DEFAULT_TEXT_PROCESSOR_CONFIG

logger = get_screenplay_logger("text_processors.config_generation")

# Only these sections contribute to the semantic pipeline hash
_PIPELINE_KEYS = ("preprocessors", "processors")

# sts_metadata "mode" values
MODE_STANDALONE = "standalone"
MODE_USER_DEFAULT = "user_default"

# sts_metadata "seeded_from" values
SEEDED_FROM_SHIPPED = "shipped_default"
SEEDED_FROM_USER = "user_default"

# User-writable global default config; mirrors the repo path
# src/script_to_speech/text_processors/configs/default_text_processor_config.yaml
# the same way USER_VOICE_LIBRARY_PATH mirrors the repo voice library.
USER_DEFAULT_CONFIG_PATH = (
    get_user_workspace_dir()
    / "text_processors"
    / "configs"
    / "user_default_text_processor_config.yaml"
)

_GENERATED_HEADER = (
    "Text processor configuration for this screenplay.\n"
    "Generated by Script to Speech; edit freely to customize processing.\n"
    "This standalone config fully replaces the built-in defaults.\n"
    "The sts_metadata block is managed by Script to Speech -- leave it as is."
)


def _strip_notes(value: Any) -> Any:
    """Recursively drop documentary ``notes`` keys from pipeline data.

    ``notes`` are human-facing annotations shown in the editor; they carry no
    processing behavior, so they must not contribute to the semantic pipeline
    hash (otherwise editing a note would spuriously mark configs stale).
    """
    if isinstance(value, dict):
        return {k: _strip_notes(v) for k, v in value.items() if k != "notes"}
    if isinstance(value, list):
        return [_strip_notes(item) for item in value]
    return value


def compute_pipeline_hash(config_data: Optional[Dict[str, Any]]) -> str:
    """Compute a semantic hash of a config's processing pipeline.

    Only the preprocessors / processors sections contribute, and documentary
    ``notes`` keys are stripped first, so comment, formatting, and note changes
    to a config file do not affect its hash.

    Args:
        config_data: Parsed config (e.g. from yaml.safe_load), or None

    Returns:
        Hex sha256 digest of the canonicalized pipeline sections
    """
    data = config_data or {}
    pipeline = {key: _strip_notes(data.get(key)) for key in _PIPELINE_KEYS}
    canonical = json.dumps(pipeline, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def get_current_default_hash() -> str:
    """Get the pipeline hash of the currently shipped default config."""
    with open(DEFAULT_TEXT_PROCESSOR_CONFIG, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return compute_pipeline_hash(data)


def is_config_stale(config_data: Optional[Dict[str, Any]]) -> bool:
    """Check whether a config was seeded from an outdated shipped default.

    Args:
        config_data: Parsed config (e.g. from yaml.safe_load), or None

    Returns:
        True when the config records a default_config_sha256 that differs from
        the currently shipped default's pipeline hash. Configs without
        provenance metadata are never considered stale.
    """
    if not isinstance(config_data, dict):
        return False

    metadata = config_data.get("sts_metadata")
    if not isinstance(metadata, dict):
        return False

    recorded_hash = metadata.get("default_config_sha256")
    if not recorded_hash:
        return False

    return bool(recorded_hash != get_current_default_hash())


def get_text_processor_config_path(json_path: str) -> str:
    """
    Get the path for a text processor configuration file based on a JSON file path.

    Args:
        json_path: Path to the JSON file

    Returns:
        Path to the text processor configuration file
    """
    json_path_obj = Path(json_path)
    config_filename = f"{json_path_obj.stem}_text_processor_config.yaml"
    return str(json_path_obj.parent / config_filename)


def _create_yaml() -> YAML:
    """Create a ruamel YAML instance configured to preserve source formatting."""
    ruamel_yaml = YAML()
    ruamel_yaml.preserve_quotes = True
    ruamel_yaml.width = 4096  # Prevent line wrapping
    ruamel_yaml.indent(mapping=2, sequence=4, offset=2)
    return ruamel_yaml


def build_seeded_config_text(source_text: str, metadata: Dict[str, Any]) -> str:
    """Build the text of a seeded config from a source config's text.

    Preserves the source's comments (they document the default rules) via a
    ruamel round-trip, replaces any existing sts_metadata block with the
    provided one, and prepends an explanatory header comment.

    Args:
        source_text: Full YAML text of the config to seed from
        metadata: sts_metadata block to embed

    Returns:
        YAML text of the seeded config

    Raises:
        ValueError: If the source text is not a YAML mapping
    """
    ruamel_yaml = _create_yaml()
    data = ruamel_yaml.load(StringIO(source_text))

    if data is None:
        data = CommentedMap()
    elif not isinstance(data, dict):
        raise ValueError("Source text processor config is not a YAML mapping")

    data.pop("sts_metadata", None)
    data.insert(0, "sts_metadata", CommentedMap(metadata))
    data.yaml_set_comment_before_after_key("sts_metadata", before=_GENERATED_HEADER)

    output = StringIO()
    ruamel_yaml.dump(data, output)
    return output.getvalue()


def _user_default_seed() -> Tuple[Path, str, str]:
    """Get seed provenance for the user's global default config.

    The recorded shipped-default hash is carried forward (that is what the
    user default's content derives from).

    Raises:
        ValueError: If the user default is not a YAML mapping
        OSError / yaml.YAMLError: If the file cannot be read or parsed
    """
    with open(USER_DEFAULT_CONFIG_PATH, "r", encoding="utf-8") as f:
        user_data = yaml.safe_load(f)
    if not isinstance(user_data, dict):
        raise ValueError(
            f"User default text processor config at {USER_DEFAULT_CONFIG_PATH} "
            f"is not a YAML mapping"
        )

    user_metadata = user_data.get("sts_metadata")
    carried_hash = None
    if isinstance(user_metadata, dict):
        carried_hash = user_metadata.get("default_config_sha256")

    return (
        USER_DEFAULT_CONFIG_PATH,
        SEEDED_FROM_USER,
        carried_hash or get_current_default_hash(),
    )


def _resolve_seed_source() -> Tuple[Path, str, str]:
    """Resolve which config to seed from and its provenance.

    Returns:
        Tuple of (source_path, seeded_from, default_config_sha256). Prefers the
        user's global default when present and readable, otherwise the shipped
        default.
    """
    if os.path.exists(USER_DEFAULT_CONFIG_PATH):
        try:
            return _user_default_seed()
        except Exception as e:
            logger.warning(
                f"Could not use user default text processor config at "
                f"{USER_DEFAULT_CONFIG_PATH}: {e}; falling back to shipped default"
            )

    return (
        DEFAULT_TEXT_PROCESSOR_CONFIG,
        SEEDED_FROM_SHIPPED,
        get_current_default_hash(),
    )


def seed_config_text(source: str = "auto") -> str:
    """Build the text of a seeded standalone config.

    Args:
        source: "auto" (user default when present, else shipped default),
            "shipped_default", or "user_default" (raises if missing/invalid)

    Returns:
        YAML text of the seeded standalone config
    """
    if source == "auto":
        source_path, seeded_from, default_hash = _resolve_seed_source()
    elif source == SEEDED_FROM_SHIPPED:
        source_path = DEFAULT_TEXT_PROCESSOR_CONFIG
        seeded_from = SEEDED_FROM_SHIPPED
        default_hash = get_current_default_hash()
    elif source == SEEDED_FROM_USER:
        source_path, seeded_from, default_hash = _user_default_seed()
    else:
        raise ValueError(f"Unknown seed source: {source}")

    with open(source_path, "r", encoding="utf-8") as f:
        source_text = f.read()

    metadata = {
        "mode": MODE_STANDALONE,
        "seeded_from": seeded_from,
        "seeded_by_version": __version__,
        "default_config_sha256": default_hash,
    }
    return build_seeded_config_text(source_text, metadata)


def generate_text_processor_config(json_path: str) -> str:
    """
    Generate a standalone text processor configuration file for a screenplay JSON file.
    The file will be named [json_filename]_text_processor_config.yaml and placed in the
    same directory, seeded from the user's global default config if one exists,
    otherwise from the shipped default config.
    If the file already exists, it will not be overwritten.

    Args:
        json_path: Path to the JSON file

    Returns:
        Path to the generated or existing config file
    """
    config_path = get_text_processor_config_path(json_path)

    # Check if the file already exists
    if os.path.exists(config_path):
        return config_path

    config_text = seed_config_text("auto")

    with open(config_path, "w", encoding="utf-8") as f:
        f.write(config_text)
    logger.info(f"Generated text processor config at {config_path}")

    return config_path
